# @format
bot:
  ID: '000000000'
  TOKEN: 'MTM2OTU4ODExMjY1MjUwNTEzMA.GlS9Xw.0mtySP8FryUitqkhwlWT2BepSMIXwZ6MW85quo'
  PREFIX: '?'
  EMBED_COLOR: '#ff0000'
  OWNERS: ['1191627654386950214']
  MONGO: 'mongodb+srv://codex-in2:codex-in2@codex-in2.gjv2c.mongodb.net/?retryWrites=true&w=majority'
links:
  INVITE: 'https://discord.com/oauth2/authorize?client_id=0000000000&permissions=8&scope=applications.commands%20bot'
  SUPPORT: 'https://dsc.gg/codexdev'
  VOTE: 'https://top.gg/bot/0000000/vote'
